// v1.0
export const AIRLINE_NAMES: Record<string, string> = {
  SQ: "Singapore Airlines", EK: "Emirates", QR: "Qatar Airways", CX: "Cathay Pacific",
  TG: "Thai Airways", MH: "Malaysia Airlines", GA: "Garuda Indonesia", AI: "Air India",
  NH: "All Nippon Airways", JL: "Japan Airlines", AA: "American Airlines",
  DL: "Delta Air Lines", UA: "United Airlines", BA: "British Airways",
  LH: "Lufthansa", AF: "Air France", KL: "KLM", EY: "Etihad Airways",
  ET: "Ethiopian Airlines", OZ: "Asiana Airlines", KE: "Korean Air",
  CI: "China Airlines", BR: "EVA Air", VN: "Vietnam Airlines",
  MU: "China Eastern", CA: "Air China", CZ: "China Southern",
  SU: "Aeroflot", TK: "Turkish Airlines", LX: "Swiss International",
  OS: "Austrian Airlines", IB: "Iberia", TP: "TAP Air Portugal",
  MS: "EgyptAir", QF: "Qantas", NZ: "Air New Zealand", VA: "Virgin Australia",
  AC: "Air Canada", WS: "WestJet", FR: "Ryanair", U2: "easyJet",
  W6: "Wizz Air", VY: "Vueling", AZ: "ITA Airways", G3: "Gol Linhas Aereas",
  LA: "LATAM Airlines", AD: "Azul Brazilian Airlines", WN: "Southwest Airlines",
  B6: "JetBlue Airways", AS: "Alaska Airlines", F9: "Frontier Airlines",
  NK: "Spirit Airlines", G4: "Allegiant Air", SY: "Sun Country Airlines",
  _3K: "Jetstar Asia", JQ: "Jetstar", TR: "Scoot", D7: "AirAsia X",
  AK: "AirAsia", FD: "Thai AirAsia", XT: "Indonesia AirAsia X",
  QZ: "Indonesia AirAsia", Z2: "Philippines AirAsia", _5J: "Cebu Pacific",
  PR: "Philippine Airlines", _2P: "PAL Express", OD: "Malindo Air",
  FY: "Firefly", _6E: "IndiGo", SG: "SpiceJet", _9W: "Jet Airways",
  _6P: "IndiGo Express", IX: "Air India Express", I5: "Air Asia India",
  QG: "Citilink", KD: "Kalstar Aviation", ID: "Batik Air",
  XW: "NokScoot", DD: "Nok Air", PG: "Bangkok Airways",
  FZ: "flydubai", G9: "Air Arabia", WY: "Oman Air", GF: "Gulf Air",
  KU: "Kuwait Airways", ME: "Middle East Airlines", RJ: "Royal Jordanian",
  UL: "SriLankan Airlines", BG: "Biman Bangladesh", _9P: "Thai Smile",
  ZH: "Shenzhen Airlines", HO: "Juneyao Airlines", HU: "Hainan Airlines",
  SC: "Shandong Airlines", GS: "Tianjin Airlines", ZG: "China Express Airlines",
  PN: "China West Air", GJ: "Loong Air", QW: "Beijing Capital Airlines",
  BK: "Okay Airways", NS: "Hebei Airlines", _8L: "Lucky Air",
  CN: "Grand China Air", UQ: "Urumqi Air", EU: "Chengdu Airlines",
  TV: "Tibet Airlines", Y8: "Loong Air", AH: "Air Algerie",
  AT: "Royal Air Maroc", CM: "Copa Airlines", AM: "Aeromexico",
  VB: "Aerobus", Y4: "Volaris", _4O: "Interjet", HA: "Hawaiian Airlines",
  multi: "Multiple Airlines",
};
export type Airline = keyof typeof AIRLINE_NAMES;
