// v1.0
export const AIRPORT_NAMES: Record<string, string> = {
  // North America
  JFK: "New York (JFK - John F. Kennedy)", LGA: "New York (LGA - LaGuardia)", EWR: "New York (EWR - Newark)",
  LAX: "Los Angeles (LAX)", SFO: "San Francisco (SFO)", SJC: "San Jose (SJC)", OAK: "Oakland (OAK)",
  ORD: "Chicago (ORD - O'Hare)", MDW: "Chicago (MDW - Midway)", ATL: "Atlanta (ATL)",
  DFW: "Dallas (DFW)", DAL: "Dallas (DAL - Love Field)", DEN: "Denver (DEN)",
  SEA: "Seattle (SEA)", PDX: "Portland (PDX)", LAS: "Las Vegas (LAS)",
  PHX: "Phoenix (PHX)", SAN: "San Diego (SAN)", MIA: "Miami (MIA)",
  FLL: "Fort Lauderdale (FLL)", MCO: "Orlando (MCO)", TPA: "Tampa (TPA)",
  BOS: "Boston (BOS)", PHL: "Philadelphia (PHL)", DCA: "Washington DC (DCA)",
  IAD: "Washington DC (IAD - Dulles)", BWI: "Baltimore (BWI)",
  MSP: "Minneapolis (MSP)", DTW: "Detroit (DTW)", CLE: "Cleveland (CLE)",
  PIT: "Pittsburgh (PIT)", CVG: "Cincinnati (CVG)", CMH: "Columbus (CMH)",
  IND: "Indianapolis (IND)", STL: "St. Louis (STL)", MCI: "Kansas City (MCI)",
  MSY: "New Orleans (MSY)", HOU: "Houston (HOU - Hobby)", IAH: "Houston (IAH - Bush)",
  AUS: "Austin (AUS)", SAT: "San Antonio (SAT)", OKC: "Oklahoma City (OKC)",
  TUL: "Tulsa (TUL)", ABQ: "Albuquerque (ABQ)", ELP: "El Paso (ELP)",
  SLC: "Salt Lake City (SLC)", BOI: "Boise (BOI)", GEG: "Spokane (GEG)",
  BUR: "Burbank (BUR)", ONT: "Ontario CA (ONT)", SNA: "Orange County (SNA)",
  PSP: "Palm Springs (PSP)", SMF: "Sacramento (SMF)", RNO: "Reno (RNO)",
  HNL: "Honolulu (HNL)", OGG: "Maui (OGG)", KOA: "Kona (KOA)",
  ANC: "Anchorage (ANC)", FAI: "Fairbanks (FAI)", JNU: "Juneau (JNU)",
  YYZ: "Toronto (YYZ)", YVR: "Vancouver (YVR)", YUL: "Montreal (YUL)",
  YOW: "Ottawa (YOW)", YEG: "Edmonton (YEG)", YYC: "Calgary (YYC)",
  YWG: "Winnipeg (YWG)", YHZ: "Halifax (YHZ)", YQB: "Quebec City (YQB)",
  MEX: "Mexico City (MEX)", GDL: "Guadalajara (GDL)", MTY: "Monterrey (MTY)",
  CUN: "Cancun (CUN)", SJD: "Los Cabos (SJD)", PVR: "Puerto Vallarta (PVR)",
  MID: "Merida (MID)", OAX: "Oaxaca (OAX)", TLC: "Toluca (TLC)",
  // South America
  GRU: "Sao Paulo (GRU - Guarulhos)", CGH: "Sao Paulo (CGH - Congonhas)",
  GIG: "Rio de Janeiro (GIG - Galeao)", SDU: "Rio de Janeiro (SDU - Santos Dumont)",
  BSB: "Brasilia (BSB)", SSA: "Salvador (SSA)", FOR: "Fortaleza (FOR)",
  REC: "Recife (REC)", BEL: "Belem (BEL)", MAO: "Manaus (MAO)",
  CWB: "Curitiba (CWB)", POA: "Porto Alegre (POA)", CNF: "Belo Horizonte (CNF)",
  EZE: "Buenos Aires (EZE - Ezeiza)", AEP: "Buenos Aires (AEP - Jorge Newbery)",
  SCL: "Santiago (SCL)", LIM: "Lima (LIM)", BOG: "Bogota (BOG)",
  MDE: "Medellin (MDE)", CLO: "Cali (CLO)", CTG: "Cartagena (CTG)",
  GYE: "Guayaquil (GYE)", UIO: "Quito (UIO)", CCS: "Caracas (CCS)",
  PTY: "Panama City (PTY)", SAL: "San Salvador (SAL)", GUA: "Guatemala City (GUA)",
  SJO: "San Jose CR (SJO)", MGA: "Managua (MGA)", TGU: "Tegucigalpa (TGU)",
  HAV: "Havana (HAV)", SDQ: "Santo Domingo (SDQ)", PAP: "Port-au-Prince (PAP)",
  KIN: "Kingston (KIN)", MBJ: "Montego Bay (MBJ)", NAS: "Nassau (NAS)",
  BGI: "Barbados (BGI)", POS: "Port of Spain (POS)", PUJ: "Punta Cana (PUJ)",
  // Europe
  LHR: "London (LHR - Heathrow)", LGW: "London (LGW - Gatwick)", LCY: "London (LCY - City)",
  STN: "London (STN - Stansted)", LTN: "London (LTN - Luton)",
  CDG: "Paris (CDG - Charles de Gaulle)", ORY: "Paris (ORY - Orly)",
  AMS: "Amsterdam (AMS)", FRA: "Frankfurt (FRA)", MUC: "Munich (MUC)",
  DUS: "Dusseldorf (DUS)", HAM: "Hamburg (HAM)", BER: "Berlin (BER)",
  ZRH: "Zurich (ZRH)", GVA: "Geneva (GVA)", VIE: "Vienna (VIE)",
  BRU: "Brussels (BRU)", MAD: "Madrid (MAD)", BCN: "Barcelona (BCN)",
  VLC: "Valencia (VLC)", AGP: "Malaga (AGP)", PMI: "Palma de Mallorca (PMI)",
  TFS: "Tenerife South (TFS)", LPA: "Gran Canaria (LPA)",
  LIS: "Lisbon (LIS)", OPO: "Porto (OPO)", FAO: "Faro (FAO)",
  FCO: "Rome (FCO - Fiumicino)", CIA: "Rome (CIA - Ciampino)",
  MXP: "Milan (MXP - Malpensa)", LIN: "Milan (LIN - Linate)", BGY: "Milan (BGY - Bergamo)",
  VCE: "Venice (VCE)", NAP: "Naples (NAP)", BLQ: "Bologna (BLQ)",
  CTA: "Catania (CTA)", PMO: "Palermo (PMO)", FLR: "Florence (FLR)",
  ATH: "Athens (ATH)", SKG: "Thessaloniki (SKG)", HER: "Heraklion (HER)",
  JMK: "Mykonos (JMK)", JTR: "Santorini (JTR)", RHO: "Rhodes (RHO)",
  CFU: "Corfu (CFU)", KGS: "Kos (KGS)", ZTH: "Zakynthos (ZTH)",
  PRG: "Prague (PRG)", BUD: "Budapest (BUD)", WAW: "Warsaw (WAW)",
  KRK: "Krakow (KRK)", GDN: "Gdansk (GDN)", WRO: "Wroclaw (WRO)",
  OSL: "Oslo (OSL)", BGO: "Bergen (BGO)", SVG: "Stavanger (SVG)",
  ARN: "Stockholm (ARN)", GOT: "Gothenburg (GOT)", MMX: "Malmo (MMX)",
  CPH: "Copenhagen (CPH)", HEL: "Helsinki (HEL)", RIX: "Riga (RIX)",
  TLL: "Tallinn (TLL)", VNO: "Vilnius (VNO)", KBP: "Kyiv (KBP)",
  SVO: "Moscow (SVO - Sheremetyevo)", DME: "Moscow (DME - Domodedovo)",
  LED: "St. Petersburg (LED)", AER: "Sochi (AER)",
  IST: "Istanbul (IST)", SAW: "Istanbul (SAW - Sabiha)",
  ESB: "Ankara (ESB)", AYT: "Antalya (AYT)", DLM: "Dalaman (DLM)",
  ADB: "Izmir (ADB)", BJV: "Bodrum (BJV)",
  // Middle East
  DXB: "Dubai (DXB)", AUH: "Abu Dhabi (AUH)", SHJ: "Sharjah (SHJ)",
  DOH: "Doha (DOH)", KWI: "Kuwait City (KWI)", BAH: "Bahrain (BAH)",
  MCT: "Muscat (MCT)", JED: "Jeddah (JED)", RUH: "Riyadh (RUH)",
  TLV: "Tel Aviv (TLV)", AMM: "Amman (AMM)", BEY: "Beirut (BEY)",
  BGW: "Baghdad (BGW)", NJF: "Najaf (NJF)", GYD: "Baku (GYD)",
  EVN: "Yerevan (EVN)", TBS: "Tbilisi (TBS)",
  // Africa
  CAI: "Cairo (CAI)", HRG: "Hurghada (HRG)", SSH: "Sharm El Sheikh (SSH)",
  LXR: "Luxor (LXR)", ASW: "Aswan (ASW)", CMN: "Casablanca (CMN)",
  RAK: "Marrakech (RAK)", TNG: "Tangier (TNG)", TUN: "Tunis (TUN)",
  DJE: "Djerba (DJE)", ALG: "Algiers (ALG)", ORN: "Oran (ORN)",
  LOS: "Lagos (LOS)", ABV: "Abuja (ABV)", KAN: "Kano (KAN)",
  ACC: "Accra (ACC)", ABJ: "Abidjan (ABJ)", DKR: "Dakar (DKR)",
  NBO: "Nairobi (NBO)", MBA: "Mombasa (MBA)", EBB: "Entebbe (EBB)",
  DAR: "Dar es Salaam (DAR)", JRO: "Kilimanjaro (JRO)", ZNZ: "Zanzibar (ZNZ)",
  ADD: "Addis Ababa (ADD)", KGL: "Kigali (KGL)", LUN: "Lusaka (LUN)",
  HRE: "Harare (HRE)", BLZ: "Blantyre (BLZ)", MRU: "Mauritius (MRU)",
  RUN: "Reunion (RUN)", SEZ: "Seychelles (SEZ)", TNR: "Antananarivo (TNR)",
  JNB: "Johannesburg (JNB)", CPT: "Cape Town (CPT)", DUR: "Durban (DUR)",
  PLZ: "Port Elizabeth (PLZ)", GRJ: "George (GRJ)",
  // South Asia
  DEL: "New Delhi (DEL)", BOM: "Mumbai (BOM)", BLR: "Bangalore (BLR)",
  MAA: "Chennai (MAA)", CCU: "Kolkata (CCU)", HYD: "Hyderabad (HYD)",
  AMD: "Ahmedabad (AMD)", PNQ: "Pune (PNQ)", COK: "Kochi (COK)",
  IXC: "Chandigarh (IXC)", LKO: "Lucknow (LKO)", PAT: "Patna (PAT)",
  KTM: "Kathmandu (KTM)", CMB: "Colombo (CMB)", DAC: "Dhaka (DAC)",
  CGP: "Chittagong (CGP)", ISB: "Islamabad (ISB)", KHI: "Karachi (KHI)",
  LHE: "Lahore (LHE)", PEW: "Peshawar (PEW)", MLE: "Male (MLE)",
  // Southeast Asia
  SIN: "Singapore (SIN)", KUL: "Kuala Lumpur (KUL)", BKI: "Kota Kinabalu (BKI)",
  PEN: "Penang (PEN)", JHB: "Johor Bahru (JHB)", LGK: "Langkawi (LGK)",
  CGK: "Jakarta (CGK)", DPS: "Bali (DPS)", SUB: "Surabaya (SUB)",
  UPG: "Makassar (UPG)", MDC: "Manado (MDC)", BPN: "Balikpapan (BPN)",
  BDO: "Bandung (BDO)", YOG: "Yogyakarta (YOG)", SOC: "Solo (SOC)",
  MNL: "Manila (MNL)", CEB: "Cebu (CEB)", DVO: "Davao (DVO)",
  CRK: "Clark (CRK)", KLO: "Kalibo (KLO)", ILO: "Iloilo (ILO)",
  BKK: "Bangkok (BKK - Suvarnabhumi)", DMK: "Bangkok (DMK - Don Mueang)",
  HKT: "Phuket (HKT)", CNX: "Chiang Mai (CNX)", USM: "Koh Samui (USM)",
  HDY: "Hat Yai (HDY)", KBV: "Krabi (KBV)", NST: "Nakhon Si Thammarat (NST)",
  HAN: "Hanoi (HAN)", SGN: "Ho Chi Minh City (SGN)", DAD: "Da Nang (DAD)",
  CXR: "Nha Trang (CXR)", VII: "Vinh (VII)", HPH: "Haiphong (HPH)",
  RGN: "Yangon (RGN)", MDL: "Mandalay (MDL)", PNH: "Phnom Penh (PNH)",
  REP: "Siem Reap (REP)", VTE: "Vientiane (VTE)", LPQ: "Luang Prabang (LPQ)",
  BWN: "Brunei (BWN)",
  // East Asia
  HKG: "Hong Kong (HKG)", MFM: "Macau (MFM)",
  PEK: "Beijing (PEK)", PKX: "Beijing (PKX - Daxing)",
  PVG: "Shanghai (PVG - Pudong)", SHA: "Shanghai (SHA - Hongqiao)",
  CAN: "Guangzhou (CAN)", CTU: "Chengdu (CTU)", CKG: "Chongqing (CKG)",
  XIY: "Xian (XIY)", WUH: "Wuhan (WUH)", CSX: "Changsha (CSX)",
  HGH: "Hangzhou (HGH)", NKG: "Nanjing (NKG)", SZX: "Shenzhen (SZX)",
  XMN: "Xiamen (XMN)", FOC: "Fuzhou (FOC)", TSN: "Tianjin (TSN)",
  DLC: "Dalian (DLC)", SYX: "Sanya (SYX)", HAK: "Haikou (HAK)",
  KMG: "Kunming (KMG)", NNG: "Nanning (NNG)", GYS: "Guangyuan (GYS)",
  KWE: "Guiyang (KWE)", TNA: "Jinan (TNA)", TAO: "Qingdao (TAO)",
  HRB: "Harbin (HRB)", CGQ: "Changchun (CGQ)", SHE: "Shenyang (SHE)",
  NRT: "Tokyo (NRT - Narita)", HND: "Tokyo (HND - Haneda)",
  KIX: "Osaka (KIX - Kansai)", ITM: "Osaka (ITM - Itami)",
  NGO: "Nagoya (NGO)", FUK: "Fukuoka (FUK)", CTS: "Sapporo (CTS)",
  OKA: "Okinawa (OKA)", SDJ: "Sendai (SDJ)", HIJ: "Hiroshima (HIJ)",
  ICN: "Seoul (ICN - Incheon)", GMP: "Seoul (GMP - Gimpo)",
  PUS: "Busan (PUS)", CJU: "Jeju (CJU)",
  TPE: "Taipei (TPE - Taoyuan)", TSA: "Taipei (TSA - Songshan)",
  KHH: "Kaohsiung (KHH)", RMQ: "Taichung (RMQ)",
  ULN: "Ulaanbaatar (ULN)",
  // Central Asia
  ALA: "Almaty (ALA)", NQZ: "Nur-Sultan (NQZ)", TAS: "Tashkent (TAS)",
  FRU: "Bishkek (FRU)", DYU: "Dushanbe (DYU)", ASB: "Ashgabat (ASB)",
  KBL: "Kabul (KBL)",
  // Oceania
  SYD: "Sydney (SYD)", MEL: "Melbourne (MEL)", BNE: "Brisbane (BNE)",
  PER: "Perth (PER)", ADL: "Adelaide (ADL)", CBR: "Canberra (CBR)",
  OOL: "Gold Coast (OOL)", CNS: "Cairns (CNS)", TSV: "Townsville (TSV)",
  DRW: "Darwin (DRW)", HTI: "Hamilton Island (HTI)",
  AKL: "Auckland (AKL)", WLG: "Wellington (WLG)", CHC: "Christchurch (CHC)",
  ZQN: "Queenstown (ZQN)", NPE: "Napier (NPE)",
  SUV: "Suva (SUV)", NAN: "Nadi (NAN)", APW: "Apia (APW)",
  TBU: "Tonga (TBU)", RAR: "Rarotonga (RAR)", PPT: "Papeete (PPT)",
  GUM: "Guam (GUM)", SPN: "Saipan (SPN)",
};
export type Airport = keyof typeof AIRPORT_NAMES;
